export const initialState = {
    todos: [
        {
            id: 1,
            text: "Learn React",
            status: "completed",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 2,
            text: "Learn Redux",
            status: "complete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 3,
            text: "Learn GraphQL",
            status: "incomplete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 4,
            text: "Learn Apollo",
            status: "doing",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 5,
            text: "Learn Gatsby",
            status: "underreview",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 6,
            text: "Learn Next",
            status: "overdue",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 7,
            text: "Learn Vue",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 8,
            text: "Learn Angular",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 9,
            text: "Learn Redux",
            status: "complete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 10,
            text: "Learn GraphQL",
            status: "incomplete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 11,
            text: "Learn Apollo",
            status: "doing",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 12,
            text: "Learn Gatsby",
            status: "underreview",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 13,
            text: "Learn Next",
            status: "overdue",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 14,
            text: "Learn Vue",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 15,
            text: "Learn Angular",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 16,
            text: "Learn Redux",
            status: "complete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 17,
            text: "Learn GraphQL",
            status: "incomplete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 18,
            text: "Learn Apollo",
            status: "doing",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 19,
            text: "Learn Gatsby",
            status: "underreview",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 20,
            text: "Learn Next",
            status: "overdue",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 21,
            text: "Learn Vue",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 22,
            text: "Learn Angular",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 23,
            text: "Learn Redux",
            status: "complete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 24,
            text: "Learn GraphQL",
            status: "incomplete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 25,
            text: "Learn Apollo",
            status: "doing",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 26,
            text: "Learn Gatsby",
            status: "underreview",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 27,
            text: "Learn Next",
            status: "overdue",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 28,
            text: "Learn Vue",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 29,
            text: "Learn Angular",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 30,
            text: "Learn Redux",
            status: "complete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 31,
            text: "Learn GraphQL",
            status: "incomplete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 32,
            text: "Learn Apollo",
            status: "doing",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 33,
            text: "Learn Gatsby",
            status: "underreview",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 34,
            text: "Learn Next",
            status: "overdue",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 35,
            text: "Learn Vue",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 36,
            text: "Learn Angular",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 37,
            text: "Learn Redux",
            status: "complete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 38,
            text: "Learn GraphQL",
            status: "incomplete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 39,
            text: "Learn Apollo",
            status: "doing",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 40,
            text: "Learn Gatsby",
            status: "underreview",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 41,
            text: "Learn Next",
            status: "overdue",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 42,
            text: "Learn Vue",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 43,
            text: "Learn Angular",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 44,
            text: "Learn Redux",
            status: "complete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 45,
            text: "Learn GraphQL",
            status: "incomplete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 46,
            text: "Learn Apollo",
            status: "doing",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 47,
            text: "Learn Gatsby",
            status: "underreview",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 48,
            text: "Learn Next",
            status: "overdue",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 49,
            text: "Learn Vue",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 50,
            text: "Learn Angular",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 51,
            text: "Learn Redux",
            status: "complete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 52,
            text: "Learn GraphQL",
            status: "incomplete",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 53,
            text: "Learn Apollo",
            status: "doing",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 54,
            text: "Learn Gatsby",
            status: "underreview",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 55,
            text: "Learn Next",
            status: "overdue",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 56,
            text: "Learn Vue",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
        {
            id: 57,
            text: "Learn Angular",
            status: "todo",
            clientName: "Client Name",
            taskHandlerName: "Sadik Istiak",
        },
    ],
};
